<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>TSKHook.UI</AssemblyName>
    <RootNamespace>TSKHook.UI</RootNamespace>
    <Version>0.3.4</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GamePath)\BepInEx\core\*.dll" Exclude="$(GamePath)\BepInEx\core\dobby.dll"><Private>false</Private></Reference>
    <Reference Include="$(GamePath)\BepInEx\interop\*.dll"><Private>false</Private></Reference>
    <Reference Include="$(GamePath)\BepInEx\plugins\TSKHook.dll"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
